import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding Sadhana Card database with tree structure and raw records...');

  // Clear existing data
  await prisma.sadhanaEntry.deleteMany({});
  await prisma.user.deleteMany({});
  await prisma.ruleConfig.deleteMany({});

  const passwordHash = await bcrypt.hash('password123', 10);

  // 1. Admin
  const admin = await prisma.user.create({
    data: {
      name: 'Temple Administrator',
      email: 'admin@iskcon.org',
      passwordHash,
      role: 'ADMIN',
      cardType: 'BRAHMACHARI_S1',
      phone: '+91 9876543210',
    },
  });

  // 2. Counsellor (ABC Prabhu)
  const counsellor = await prisma.user.create({
    data: {
      name: 'HG ABC Prabhu (Counsellor)',
      email: 'counsellor.abc@iskcon.org',
      passwordHash,
      role: 'COUNSELLOR',
      cardType: 'BRAHMACHARI_S1',
      phone: '+91 9876543211',
    },
  });

  // 3. Brahmacharis under ABC Prabhu
  const brahmachariXyz = await prisma.user.create({
    data: {
      name: 'XYZ Das Brahmachari',
      email: 'brahmachari.xyz@iskcon.org',
      passwordHash,
      role: 'BRAHMACHARI',
      cardType: 'BRAHMACHARI_S1',
      phone: '+91 9876543212',
      counsellorId: counsellor.id,
    },
  });

  const brahmachariMohan = await prisma.user.create({
    data: {
      name: 'Mohan Das Brahmachari',
      email: 'brahmachari.mohan@iskcon.org',
      passwordHash,
      role: 'BRAHMACHARI',
      cardType: 'BRAHMACHARI_S1',
      phone: '+91 9876543213',
      counsellorId: counsellor.id,
    },
  });

  // 4. Students under Brahmachari XYZ Das
  const student1 = await prisma.user.create({
    data: {
      name: 'Student 1 (Gaurav Kumar)',
      email: 'student1@iskcon.org',
      passwordHash,
      role: 'STUDENT',
      cardType: 'STUDENT_S2',
      phone: '+91 9876543220',
      counsellorId: counsellor.id,
      preacherId: brahmachariXyz.id,
    },
  });

  const student2 = await prisma.user.create({
    data: {
      name: 'Student 2 (Ramesh Sharma)',
      email: 'student2@iskcon.org',
      passwordHash,
      role: 'STUDENT',
      cardType: 'STUDENT_S2',
      phone: '+91 9876543221',
      counsellorId: counsellor.id,
      preacherId: brahmachariXyz.id,
    },
  });

  // 5. Students under Mohan Das
  const student3 = await prisma.user.create({
    data: {
      name: 'Student 3 (Amit Verma)',
      email: 'student3@iskcon.org',
      passwordHash,
      role: 'STUDENT',
      cardType: 'STUDENT_S2',
      phone: '+91 9876543222',
      counsellorId: counsellor.id,
      preacherId: brahmachariMohan.id,
    },
  });

  console.log('Created Users & Tree:');
  console.log(`- Counsellor: ${counsellor.name}`);
  console.log(`  - Brahmachari: ${brahmachariXyz.name}`);
  console.log(`    - Student: ${student1.name}`);
  console.log(`    - Student: ${student2.name}`);
  console.log(`  - Brahmachari: ${brahmachariMohan.name}`);
  console.log(`    - Student: ${student3.name}`);

  // Seed 15 days of Raw Sadhana Data (2026-09-01 to 2026-09-15) for XYZ Das (Brahmachari)
  const brahmachariRawLogs = [
    {
      date: '2026-09-01',
      sleepBedTime: '21:55',
      wakeUpTime: '03:40',
      daySleepMinutes: 45,
      japaCompletionTime: '07:10',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 75,
      pathanBookName: 'Bhagavad-gita As It Is Ch. 9',
      sravanMinutes: 80,
      sravanLectureTopic: 'Srila Prabhupada SB 1.2.6',
      sevaPreaching: 180,
      sevaManagement: 120,
      sevaLecturePrep: 60,
      sevaMenial: 40,
      sevaHarinamBook: 60,
      sevaAdhocTravel: 30,
      sevaMisc: 20,
      sevaNotes: 'BACE student weekly counseling session & evening kirtan',
      bhavanaNegativeTags: JSON.stringify(['M']),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D', 'H']),
      personalNotes: 'Felt deep taste in morning japa and SB class.',
    },
    {
      date: '2026-09-02',
      sleepBedTime: '22:04',
      wakeUpTime: '03:45',
      daySleepMinutes: 50,
      japaCompletionTime: '07:12',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 65,
      pathanBookName: 'Srimad Bhagavatam Canto 2',
      sravanMinutes: 60,
      sravanLectureTopic: 'HG Radheshyam Prabhu lecture on Sadhana',
      sevaPreaching: 150,
      sevaManagement: 90,
      sevaLecturePrep: 45,
      sevaMenial: 60,
      sevaHarinamBook: 90,
      sevaAdhocTravel: 20,
      sevaMisc: 15,
      sevaNotes: 'Youth festival planning and temple service',
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'PT', 'GS']),
      personalNotes: 'Good team coordination during festival preparation.',
    },
    {
      date: '2026-09-03',
      sleepBedTime: '22:05',
      wakeUpTime: '03:45',
      daySleepMinutes: 20,
      japaCompletionTime: '07:10',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 80,
      pathanBookName: 'Teachings of Lord Caitanya',
      sravanMinutes: 60,
      sravanLectureTopic: 'Srila Prabhupada Arrival in Boston',
      sevaPreaching: 210,
      sevaManagement: 60,
      sevaLecturePrep: 60,
      sevaMenial: 30,
      sevaHarinamBook: 120,
      sevaAdhocTravel: 30,
      sevaMisc: 20,
      sevaNotes: 'Harinam Sankirtan at Greater Noida market',
      bhavanaNegativeTags: JSON.stringify(['U']),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D', 'F']),
      personalNotes: 'Energetic book distribution & sweet chanting.',
    },
    {
      date: '2026-09-04',
      sleepBedTime: '22:15',
      wakeUpTime: '03:52',
      daySleepMinutes: 60,
      japaCompletionTime: '08:15',
      japaRoundsCount: 16,
      mangalAarti: 'LATE',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 60,
      pathanBookName: 'Nectar of Devotion',
      sravanMinutes: 60,
      sravanLectureTopic: 'Bhakti Rasamrita Sindhu Ocean overview',
      sevaPreaching: 120,
      sevaManagement: 120,
      sevaLecturePrep: 60,
      sevaMenial: 45,
      sevaHarinamBook: 60,
      sevaAdhocTravel: 45,
      sevaMisc: 30,
      sevaNotes: 'Library maintenance and counseling call',
      bhavanaNegativeTags: JSON.stringify(['L']),
      bhavanaPositiveTags: JSON.stringify(['PT', 'H']),
      personalNotes: 'Woke up a bit late, made up with extra hearing.',
    },
    {
      date: '2026-09-05',
      sleepBedTime: '22:00',
      wakeUpTime: '03:40',
      daySleepMinutes: 40,
      japaCompletionTime: '07:05',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 90,
      pathanBookName: 'Sri Isopanisad Mantra 1-4',
      sravanMinutes: 90,
      sravanLectureTopic: 'Srila Prabhupada Vyasa-puja lectures',
      sevaPreaching: 240,
      sevaManagement: 60,
      sevaLecturePrep: 90,
      sevaMenial: 30,
      sevaHarinamBook: 90,
      sevaAdhocTravel: 30,
      sevaMisc: 0,
      sevaNotes: 'Sunday feast preparation & Youth satsang',
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D', 'GS', 'T']),
      personalNotes: 'Enthusiastic Sunday feast preaching and attendance.',
    },
    {
      date: '2026-09-06',
      sleepBedTime: '22:05',
      wakeUpTime: '03:45',
      daySleepMinutes: 45,
      japaCompletionTime: '07:14',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 60,
      pathanBookName: 'Chaitanya Charitamrita Adi 1',
      sravanMinutes: 70,
      sravanLectureTopic: 'Glories of Pancha Tattva',
      sevaPreaching: 200,
      sevaManagement: 100,
      sevaLecturePrep: 40,
      sevaMenial: 30,
      sevaHarinamBook: 60,
      sevaAdhocTravel: 30,
      sevaMisc: 20,
      sevaNotes: 'Temple cleaning & New devotees reception',
      bhavanaNegativeTags: JSON.stringify(['M']),
      bhavanaPositiveTags: JSON.stringify(['H', 'PT']),
      personalNotes: 'Practiced humble listening.',
    },
    {
      date: '2026-09-07',
      sleepBedTime: '21:50',
      wakeUpTime: '03:35',
      daySleepMinutes: 30,
      japaCompletionTime: '07:00',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 90,
      pathanBookName: 'Srimad Bhagavatam Canto 1 Ch 3',
      sravanMinutes: 75,
      sravanLectureTopic: 'Incarnations of the Supreme Lord',
      sevaPreaching: 180,
      sevaManagement: 90,
      sevaLecturePrep: 60,
      sevaMenial: 45,
      sevaHarinamBook: 90,
      sevaAdhocTravel: 30,
      sevaMisc: 15,
      sevaNotes: 'Prasadam distribution and counselling',
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D', 'GS']),
      personalNotes: 'Very peaceful Day 7 conclusion.',
    },
    // Week 2 logs: Sep 8 to Sep 15
    {
      date: '2026-09-08',
      sleepBedTime: '22:00',
      wakeUpTime: '03:40',
      daySleepMinutes: 45,
      japaCompletionTime: '07:10',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 70,
      pathanBookName: 'Bhagavad-gita Ch 12',
      sravanMinutes: 65,
      sravanLectureTopic: 'Bhakti Yoga Essence',
      sevaPreaching: 160,
      sevaManagement: 110,
      sevaLecturePrep: 50,
      sevaMenial: 40,
      sevaHarinamBook: 70,
      sevaAdhocTravel: 30,
      sevaMisc: 20,
      sevaNotes: 'Preaching in college hostel',
      bhavanaNegativeTags: JSON.stringify(['E']),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'T']),
    },
    {
      date: '2026-09-09',
      sleepBedTime: '22:08',
      wakeUpTime: '03:48',
      daySleepMinutes: 55,
      japaCompletionTime: '07:15',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 60,
      pathanBookName: 'Sri Isopanisad Mantra 5-8',
      sravanMinutes: 60,
      sravanLectureTopic: 'Ishavasya Principle',
      sevaPreaching: 190,
      sevaManagement: 80,
      sevaLecturePrep: 60,
      sevaMenial: 30,
      sevaHarinamBook: 80,
      sevaAdhocTravel: 40,
      sevaMisc: 20,
      sevaNotes: 'Meeting with BACE devotees',
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['PT', 'H', 'D']),
    },
    {
      date: '2026-09-10',
      sleepBedTime: '22:00',
      wakeUpTime: '03:42',
      daySleepMinutes: 45,
      japaCompletionTime: '07:08',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 80,
      pathanBookName: 'Nectar of Instruction Upadesamrta',
      sravanMinutes: 70,
      sravanLectureTopic: 'Six Destructive & Six Favorable items',
      sevaPreaching: 200,
      sevaManagement: 90,
      sevaLecturePrep: 60,
      sevaMenial: 40,
      sevaHarinamBook: 90,
      sevaAdhocTravel: 30,
      sevaMisc: 10,
      sevaNotes: 'Youth counseling and kitchen service',
      bhavanaNegativeTags: JSON.stringify(['P']),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'GS']),
    },
    {
      date: '2026-09-11',
      sleepBedTime: '22:12',
      wakeUpTime: '03:45',
      daySleepMinutes: 60,
      japaCompletionTime: '07:14',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 60,
      pathanBookName: 'Bhagavad-gita Ch 14',
      sravanMinutes: 60,
      sravanLectureTopic: 'Three Modes of Material Nature',
      sevaPreaching: 150,
      sevaManagement: 120,
      sevaLecturePrep: 45,
      sevaMenial: 45,
      sevaHarinamBook: 60,
      sevaAdhocTravel: 40,
      sevaMisc: 20,
      sevaNotes: 'Temple accounting & guest hosting',
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['PT', 'H']),
    },
    {
      date: '2026-09-12',
      sleepBedTime: '22:05',
      wakeUpTime: '03:40',
      daySleepMinutes: 45,
      japaCompletionTime: '07:09',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 75,
      pathanBookName: 'Srimad Bhagavatam Canto 1 Ch 7',
      sravanMinutes: 80,
      sravanLectureTopic: 'Punishment of Asvatthama',
      sevaPreaching: 220,
      sevaManagement: 70,
      sevaLecturePrep: 60,
      sevaMenial: 30,
      sevaHarinamBook: 100,
      sevaAdhocTravel: 30,
      sevaMisc: 10,
      sevaNotes: 'Weekly youth retreat prep',
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D', 'F']),
    },
    {
      date: '2026-09-13',
      sleepBedTime: '22:00',
      wakeUpTime: '03:44',
      daySleepMinutes: 50,
      japaCompletionTime: '07:11',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 65,
      pathanBookName: 'Srimad Bhagavatam Canto 1 Ch 8',
      sravanMinutes: 65,
      sravanLectureTopic: 'Queen Kunti Prayers',
      sevaPreaching: 230,
      sevaManagement: 60,
      sevaLecturePrep: 60,
      sevaMenial: 30,
      sevaHarinamBook: 80,
      sevaAdhocTravel: 30,
      sevaMisc: 20,
      sevaNotes: 'Sunday Feast Harinam & Kirtan',
      bhavanaNegativeTags: JSON.stringify(['M']),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'GS', 'H']),
    },
    {
      date: '2026-09-14',
      sleepBedTime: '22:03',
      wakeUpTime: '03:40',
      daySleepMinutes: 40,
      japaCompletionTime: '07:05',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 70,
      pathanBookName: 'Bhagavad-gita Ch 18',
      sravanMinutes: 70,
      sravanLectureTopic: 'Conclusion of BG - Sarva Dharman Parityajya',
      sevaPreaching: 180,
      sevaManagement: 90,
      sevaLecturePrep: 60,
      sevaMenial: 40,
      sevaHarinamBook: 70,
      sevaAdhocTravel: 30,
      sevaMisc: 10,
      sevaNotes: 'BACE student card evaluations',
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D', 'PT']),
    },
    {
      date: '2026-09-15',
      sleepBedTime: '22:10',
      wakeUpTime: '03:45',
      daySleepMinutes: 45,
      japaCompletionTime: '07:12',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      guruPuja: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 65,
      pathanBookName: 'Nectar of Instruction Verses 1-3',
      sravanMinutes: 60,
      sravanLectureTopic: 'Controlling Six Urges',
      sevaPreaching: 170,
      sevaManagement: 100,
      sevaLecturePrep: 50,
      sevaMenial: 35,
      sevaHarinamBook: 65,
      sevaAdhocTravel: 30,
      sevaMisc: 20,
      sevaNotes: 'Monthly counseling report preparation',
      bhavanaNegativeTags: JSON.stringify(['L']),
      bhavanaPositiveTags: JSON.stringify(['H', 'PT']),
    },
  ];

  for (const log of brahmachariRawLogs) {
    await prisma.sadhanaEntry.create({
      data: {
        userId: brahmachariXyz.id,
        ...log,
      },
    });
  }

  // Seed Student 1 Raw Data (BACE Student S2) for Sep 1 to 15, 2026
  const student1RawLogs = [
    {
      date: '2026-09-01',
      sleepBedTime: '22:05',
      wakeUpTime: '04:45',
      daySleepMinutes: 20,
      japaCompletionTime: '07:10',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 35,
      pathanBookName: 'Bhagavad-gita Ch 2',
      sravanMinutes: 30,
      sravanLectureTopic: 'HG Radheshyam Prabhu lecture on Mind Control',
      officeOutTime: '09:00',
      officeInTime: '18:30',
      sevaPreaching: 30,
      sevaMenial: 30,
      sevaHarinamBook: 15,
      sevaNotes: 'BACE cleaning & book setup',
      bhavanaNegativeTags: JSON.stringify(['M']),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D']),
      personalNotes: 'Good start of the month.',
    },
    {
      date: '2026-09-02',
      sleepBedTime: '22:15',
      wakeUpTime: '04:50',
      daySleepMinutes: 15,
      japaCompletionTime: '08:20',
      japaRoundsCount: 16,
      mangalAarti: 'LATE',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 30,
      pathanBookName: 'Bhagavad-gita Ch 3',
      sravanMinutes: 30,
      sravanLectureTopic: 'Karma Yoga lecture',
      officeOutTime: '09:15',
      officeInTime: '18:45',
      sevaPreaching: 25,
      sevaMenial: 30,
      sevaNotes: 'BACE kitchen cleanup',
      bhavanaNegativeTags: JSON.stringify(['L']),
      bhavanaPositiveTags: JSON.stringify(['PT']),
    },
    {
      date: '2026-09-03',
      sleepBedTime: '22:00',
      wakeUpTime: '04:40',
      daySleepMinutes: 0,
      japaCompletionTime: '07:12',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 40,
      pathanBookName: 'Science of Self Realization',
      sravanMinutes: 35,
      sravanLectureTopic: 'Definition of Guru',
      officeOutTime: '09:00',
      officeInTime: '18:30',
      sevaPreaching: 40,
      sevaMenial: 20,
      sevaNotes: 'Helping in evening college satsang',
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'GS']),
    },
    {
      date: '2026-09-04',
      sleepBedTime: '22:10',
      wakeUpTime: '04:45',
      daySleepMinutes: 20,
      japaCompletionTime: '07:15',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 30,
      pathanBookName: 'Science of Self Realization',
      sravanMinutes: 30,
      sravanLectureTopic: 'Prabhupada interview',
      officeOutTime: '09:00',
      officeInTime: '19:00',
      sevaPreaching: 20,
      sevaMenial: 30,
      sevaNotes: 'Temple prasadam packing',
      bhavanaNegativeTags: JSON.stringify(['U']),
      bhavanaPositiveTags: JSON.stringify(['H']),
    },
    {
      date: '2026-09-05',
      sleepBedTime: '22:20',
      wakeUpTime: '05:00',
      daySleepMinutes: 30,
      japaCompletionTime: '08:30',
      japaRoundsCount: 16,
      mangalAarti: 'LATE',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 30,
      pathanBookName: 'Bhagavad-gita Ch 4',
      sravanMinutes: 30,
      sravanLectureTopic: 'Transcendental Knowledge',
      officeOutTime: '09:30',
      officeInTime: '18:00',
      sevaPreaching: 60,
      sevaHarinamBook: 30,
      sevaNotes: 'Saturday book table at metro station',
      bhavanaNegativeTags: JSON.stringify(['L']),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D']),
    },
    {
      date: '2026-09-06',
      sleepBedTime: '21:55',
      wakeUpTime: '04:30',
      daySleepMinutes: 0,
      japaCompletionTime: '07:05',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 45,
      pathanBookName: 'Bhagavad-gita Ch 5',
      sravanMinutes: 45,
      sravanLectureTopic: 'Sunday Feast lecture by HG Gauranga Prabhu',
      officeOutTime: null,
      officeInTime: null,
      sevaPreaching: 120,
      sevaMenial: 60,
      sevaNotes: 'Sunday Feast prasadam serving and crowd management',
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D', 'H', 'F']),
    },
    {
      date: '2026-09-07',
      sleepBedTime: '22:05',
      wakeUpTime: '04:45',
      daySleepMinutes: 20,
      japaCompletionTime: '07:10',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 30,
      pathanBookName: 'Bhagavad-gita Ch 6',
      sravanMinutes: 30,
      sravanLectureTopic: 'Dhyana Yoga lecture',
      officeOutTime: '09:00',
      officeInTime: '18:30',
      sevaPreaching: 30,
      sevaMenial: 30,
      sevaNotes: 'BACE cleaning',
      bhavanaNegativeTags: JSON.stringify(['M']),
      bhavanaPositiveTags: JSON.stringify(['PT']),
    },
    // Student logs week 2
    {
      date: '2026-09-08',
      sleepBedTime: '22:00',
      wakeUpTime: '04:40',
      daySleepMinutes: 15,
      japaCompletionTime: '07:10',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 35,
      pathanBookName: 'Bhagavad-gita Ch 7',
      sravanMinutes: 30,
      sravanLectureTopic: 'Knowledge of the Absolute',
      officeOutTime: '09:00',
      officeInTime: '18:30',
      sevaPreaching: 30,
      sevaMenial: 25,
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D']),
    },
    {
      date: '2026-09-09',
      sleepBedTime: '22:15',
      wakeUpTime: '04:50',
      daySleepMinutes: 20,
      japaCompletionTime: '08:15',
      japaRoundsCount: 16,
      mangalAarti: 'LATE',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 30,
      pathanBookName: 'Bhagavad-gita Ch 8',
      sravanMinutes: 30,
      sravanLectureTopic: 'Attaining the Supreme',
      officeOutTime: '09:15',
      officeInTime: '18:45',
      sevaPreaching: 20,
      sevaMenial: 30,
      bhavanaNegativeTags: JSON.stringify(['L']),
      bhavanaPositiveTags: JSON.stringify(['PT']),
    },
    {
      date: '2026-09-10',
      sleepBedTime: '22:05',
      wakeUpTime: '04:45',
      daySleepMinutes: 0,
      japaCompletionTime: '07:12',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 40,
      pathanBookName: 'Bhagavad-gita Ch 9',
      sravanMinutes: 35,
      sravanLectureTopic: 'The Most Confidential Knowledge',
      officeOutTime: '09:00',
      officeInTime: '18:30',
      sevaPreaching: 40,
      sevaMenial: 20,
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'GS']),
    },
    {
      date: '2026-09-11',
      sleepBedTime: '22:00',
      wakeUpTime: '04:40',
      daySleepMinutes: 20,
      japaCompletionTime: '07:10',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 30,
      pathanBookName: 'Bhagavad-gita Ch 10',
      sravanMinutes: 30,
      sravanLectureTopic: 'The Opulence of the Absolute',
      officeOutTime: '09:00',
      officeInTime: '18:30',
      sevaPreaching: 30,
      sevaMenial: 30,
      bhavanaNegativeTags: JSON.stringify(['E']),
      bhavanaPositiveTags: JSON.stringify(['H']),
    },
    {
      date: '2026-09-12',
      sleepBedTime: '22:10',
      wakeUpTime: '04:45',
      daySleepMinutes: 15,
      japaCompletionTime: '07:14',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 35,
      pathanBookName: 'Bhagavad-gita Ch 11',
      sravanMinutes: 30,
      sravanLectureTopic: 'The Universal Form',
      officeOutTime: '09:30',
      officeInTime: '18:00',
      sevaPreaching: 45,
      sevaMenial: 25,
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D']),
    },
    {
      date: '2026-09-13',
      sleepBedTime: '22:00',
      wakeUpTime: '04:35',
      daySleepMinutes: 0,
      japaCompletionTime: '07:05',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 45,
      pathanBookName: 'Bhagavad-gita Ch 12',
      sravanMinutes: 40,
      sravanLectureTopic: 'Sunday Feast Satsang',
      officeOutTime: null,
      officeInTime: null,
      sevaPreaching: 90,
      sevaMenial: 60,
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D', 'H']),
    },
    {
      date: '2026-09-14',
      sleepBedTime: '22:05',
      wakeUpTime: '04:45',
      daySleepMinutes: 20,
      japaCompletionTime: '07:10',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 30,
      pathanBookName: 'Bhagavad-gita Ch 13',
      sravanMinutes: 30,
      sravanLectureTopic: 'Nature, Enjoyer and Consciousness',
      officeOutTime: '09:00',
      officeInTime: '18:30',
      sevaPreaching: 30,
      sevaMenial: 30,
      bhavanaNegativeTags: JSON.stringify(['M']),
      bhavanaPositiveTags: JSON.stringify(['PT']),
    },
    {
      date: '2026-09-15',
      sleepBedTime: '22:00',
      wakeUpTime: '04:40',
      daySleepMinutes: 15,
      japaCompletionTime: '07:08',
      japaRoundsCount: 16,
      mangalAarti: 'ON_TIME',
      sbClass: 'ON_TIME',
      prasadam: 'ON_TIME',
      pathanMinutes: 35,
      pathanBookName: 'Bhagavad-gita Ch 14',
      sravanMinutes: 35,
      sravanLectureTopic: 'Gunatraya Vibhaga Yoga',
      officeOutTime: '09:00',
      officeInTime: '18:30',
      sevaPreaching: 35,
      sevaMenial: 25,
      bhavanaNegativeTags: JSON.stringify([]),
      bhavanaPositiveTags: JSON.stringify(['NTU', 'D', 'H']),
    },
  ];

  for (const log of student1RawLogs) {
    await prisma.sadhanaEntry.create({
      data: {
        userId: student1.id,
        ...log,
      },
    });
  }

  console.log('Seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
